# 공통 설정
spring:
  profiles:
    active: local
  application:
    name: cart-service
  config:
    import: classpath:eventTopic.yml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.promptoven.cartservice
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui.operations-sorter: alpha

management:
  # endpoint 노출
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans,info,configprops"
      base-path: /actuator
  # endpoint 활성화/비활성화
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
      tags:
        application: ${spring.application.name}
    prometheus:
      enabled: true

logging:
  level:
    com.promptoven.cartservice: DEBUG

server:
  shutdown: graceful

# local 설정
---
spring:
  config:
    activate:
      on-profile: local
    import:
     - classpath:eventTopic.yml
  datasource:
    url: jdbc:mysql://localhost:3306/cart_service
    username: root
    password: jiwon1923
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    text-bootstrap-servers: localhost:29092,localhost:39092,localhost:49092

server:
  port: 8082

# prod 설정
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:eventTopic.yml
  datasource:
    url: jdbc:mysql://mysql:3306/cart
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    text-bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 8080
